# Formatting is critical! If you have issues, you can check your config at https://codebeautify.org/yaml-parser-online
WeaponType:
    - Name: Pistol
      DamageMultiplier: 1
    - Name: Rifle
      DamageMultiplier: 1.5
    - Name: Shotgun
      DamageMultiplier: 2
    - Name: SubmachineGun
      DamageMultiplier: 1
    - Name: MachineGun
      DamageMultiplier: 1.5
    - Name: Sniper
      DamageMultiplier: 2
    - Name: Other
      DamageMultiplier: 1
