name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        SuperPlugins_BUILD_PATH: ${{ github.workspace }}/Build
    steps:
      - uses: actions/checkout@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        
      - name: Build
        run: |
          msbuild SuperPlugins.sln /p:Configuration=Release /p:Platform="Any CPU"

      - name: Upload PyroCommon
        uses: actions/upload-artifact@v3
        with:
          name: PyroCommon
          path: D:\a\SuperPlugins\SuperPlugins\PyroCommon\bin\Release\PyroCommon.dll
          
      - name: Upload SuperCallouts
        uses: actions/upload-artifact@v3
        with:
          name: SuperCallouts
          path: D:\a\SuperPlugins\SuperPlugins\SuperCallouts\bin\Release\SuperCallouts.dll
          
      - name: Upload SuperEvents
        uses: actions/upload-artifact@v3
        with:
          name: SuperEvents
          path: D:\a\SuperPlugins\SuperPlugins\SuperEvents\bin\Release\SuperEvents.dll
          
      - name: Upload DeadlyWeapons
        uses: actions/upload-artifact@v3
        with:
          name: DeadlyWeapons
          path: D:\a\SuperPlugins\SuperPlugins\DeadlyWeapons\bin\Release\DeadlyWeapons.dll
          
      - name: Upload TurnOffThatEngine
        uses: actions/upload-artifact@v3
        with:
          name: TurnOffThatEngine
          path: D:\a\SuperPlugins\SuperPlugins\TurnOffThatEngine\bin\Release\TurnOffThatEngine.dll
