name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        config: [Release]
    env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        SuperPlugins_BUILD_PATH: ${{ github.workspace }}/Build
    steps:
      - uses: actions/checkout@v1

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.1
      
      - name: Build
        run: |
          msbuild SupwePlugins.sln /p:Configuration=${{ matrix.config }} /p:Platform=x64

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: Spotlight-${{ matrix.config }}
          path: ${{ env.SuperPlugins_BUILD_PATH }}
