name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        SuperPlugins_BUILD_PATH: ${{ github.workspace }}/Build
    steps:
      - uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        
      - name: Build
        run: |
          msbuild SuperPlugins.sln /p:Configuration=Release /p:Platform="Any CPU"

      - name: Upload Plugins
        uses: actions/upload-artifact@v4
        with:
          name: SuperPlugins
          path: C:\Coding\SPBuild\
        
