name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: windows-2019
    env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        SuperPlugins_BUILD_PATH: ${{ github.workspace }}/Build
    steps:
      - uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        
      - name: Build
        run: |
          msbuild SuperPlugins.sln /p:Configuration=Release /p:Platform="Any CPU"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          #name: SuperCallouts
          path: |
          D:\a\SuperPlugins\SuperPlugins\DeadlyWeapons2\bin\Release\DeadlyWeapons2:
            dll:
          D:\a\SuperPlugins\SuperPlugins\SuperCallouts2\bin\Release\SuperCallouts2:
            dll:
          D:\a\SuperPlugins\SuperPlugins\SuperEvents2\bin\Release\SuperEvents2:
            dll:
          D:\a\SuperPlugins\SuperPlugins\TurnOffThatEngine\bin\Release\TurnOffThatEngine:
            dll:
              