name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: windows-2019
    env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        SuperPlugins_BUILD_PATH: ${{ github.workspace }}/Build
    steps:
      - uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        
      - name: Build
        run: |
          msbuild SuperPlugins.sln /p:Configuration=Release /p:Platform="Any CPU"

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: SuperPlugins-
          path: ${{ env.SuperPlugins_BUILD_PATH }}
